version: "3"

services:     
  modbus-server:
    image: sflorenz05/modbusssihfb:modbus-server
    container_name: modbus-server
    working_dir: /app/modbus-sync-server
    volumes:
      - ../../app/modbus-sync-server:/app/modbus-sync-server
      - ../../connection-profile:/app/connection-profile
      - ../../crypto-material:/app/crypto-material
      - ../../chaincode:/app/chaincode
    command: sh -c "python3 registration.py"
    ports: 
      - 5020:5020

  modbus-client:
    image: sflorenz05/modbusssihfb:modbus-client
    container_name: modbus-client1
    depends_on: 
      - modbus-server
    working_dir: /app/modbus-sync-client
    volumes:
      - ../../app/modbus-sync-client:/app/modbus-sync-client
      - ../../connection-profile:/app/connection-profile
      - ../../crypto-material:/app/crypto-material
      - ../../chaincode:/app/chaincode
    command: sh -c "python3 registration.py"
    ports: 
      - 5021:5021