version: "3"

services:     
  modbus-server:
    image: sflorenz05/modbusssihfb:modbus-sync-base
    container_name: modbus-server
    working_dir: /app/modbus-sync-server
    volumes:
      - ../../app/modbus-sync-server/sync.py:/usr/local/lib/python3.8/dist-packages/pymodbus/server/sync.py      
      - ../../app/modbus-sync-client/hfbssisdk:/usr/local/lib/python3.8/dist-packages/hfbssisdk
      - ../../app/modbus-sync-client/client.crt:/usr/local/share/ca-certificates/client.crt
      - ../../app/modbus-sync-server:/app/modbus-sync-server
      - ../../connection-profile:/app/connection-profile
      - ../../crypto-material:/app/crypto-material
      - ../../chaincode:/app/chaincode
    command: sh -c "chmod +x /usr/local/share/ca-certificates/client.crt && update-ca-certificates && python3 registration.py"
    ports: 
      - 8020:8020

  modbus-client1:
    image: sflorenz05/modbusssihfb:modbus-sync-base
    container_name: modbus-client1
    environment: 
      - IP_SERVER=modbus-server
    depends_on: 
      - modbus-server
    working_dir: /app/modbus-sync-client
    volumes:
      - ../../app/modbus-sync-client/sync.py:/usr/local/lib/python3.8/dist-packages/pymodbus/client/sync.py
      - ../../app/modbus-sync-client/hfbssisdk:/usr/local/lib/python3.8/dist-packages/hfbssisdk
      - ../../app/modbus-sync-server/server.crt:/usr/local/share/ca-certificates/server.crt
      - ../../app/modbus-sync-client:/app/modbus-sync-client
      - ../../connection-profile:/app/connection-profile
      - ../../crypto-material:/app/crypto-material
      - ../../chaincode:/app/chaincode
    command: sh -c "./wait-for-it.sh 172.19.0.2:8020 -t 60 && chmod +x /usr/local/share/ca-certificates/server.crt && update-ca-certificates && python3 registration.py"
    ports: 
      - 8021:8021