global:
  scrape_interval: 1s
  external_labels:
    monitor: "devopsage-monitor"

scrape_configs:
  - job_name: "prometheus"

    # Retain labels, as within PushGateway use
    honor_labels: true

    static_configs:
      - targets:
          [
            "prometheus:9090",
            "pushGateway:9091",
            "orderer.example.com:9441",
            "peer0.org1.example.com:9442",
            "peer0.org2.example.com:9443",
            "peer0.org2.example.com:9444",
            "peer1.org2.example.com:9445",
          ]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]
